version: '3.9'

services:
  web:
    build: .
    ports:
      - "9999:9999"
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://postgres:Fucheng830@192.168.1.9:5433/postgres
      - EMBEDDING_MODEL_PATH=/code/m3e-base
      - IMAGE_CAPTION_MODEL_PATH=/code/blip-image-captioning-base